// Auto-generated theme list - All 112 themes
export const THEME_FILES: Record<string, string> = {
    "none": "",
    "aider": "aider.theme.css",
    "alan-walker": "alanWalker.theme.css",
    "alternative-vista": "AlternativeVistaAutoUpdate.theme.css",
    "amethyst": "amethyst.theme.css",
    "amoled-cord": "amoled-cord.theme.css",
    "azurite": "Azurite.theme.css",
    "basic-background": "BasicBackground.theme.css",
    "blurple-recolor": "BlurpleRecolor.theme.css",
    "bubble-theme": "BubbleThemev2.theme.css",
    "chillax": "chillax.theme.css",
    "clearvision": "ClearVision-v7-BetterDiscord.theme.css",
    "cursed-cord": "CursedCord.theme.css",
    "cyan": "Cyan.theme.css",
    "cyberpunk2077": "cyberpunk2077.theme.css",
    "dark-plus": "Dark+.theme.css",
    "dark-matter": "DarkMatter.theme.css",
    "dark-neon": "DarkNeon.theme.css",
    "ddex4": "ddex4.theme.css",
    "discord-reborn": "Discord Reborn.theme.css",
    "discord-mica": "discord-mica.theme.css",
    "discord11": "Discord11.theme.css",
    "discord16": "discord16.theme.css",
    "discord-dark": "discorddark.theme.css",
    "discordia": "discordia.theme.css",
    "discord-night": "DiscordNight.theme.css",
    "discord-plus": "DiscordPlus.theme.css",
    "discord-recolor": "DiscordRecolor.theme.css",
    "dtm-08": "dtm-08.theme.css",
    "dtm-16": "dtm-16.theme.css",
    "dtm-18": "dtm-18.theme.css",
    "dyslexia": "dyslexia.theme.css",
    "emoji-replace": "EmojiReplace.theme.css",
    "eris": "Eris.theme.css",
    "exponent": "Exponent.theme.css",
    "ez-light": "EzLight.theme.css",
    "fallout4": "Fallout4Terminal.theme.css",
    "fluent": "Fluent.theme.css",
    "frosted-glass": "FrostedGlass.theme.css",
    "fvui": "FVUI.theme.css",
    "ggo-kirito": "GGO_Kirito.theme.css",
    "glass-wave": "Glass Wave.theme.css",
    "glass-local": "glass_local.theme.css",
    "gruvbox-sharp": "GruvboxSharp.theme.css",
    "gxcord": "gxcord.theme.css",
    "horizontal-server": "HorizontalServerList.theme.css",
    "kaleidoscope": "kaleidoscope.theme.css",
    "material-discord": "Material-Discord.theme.css",
    "material-design": "MaterialDesign.theme.css",
    "materialistic": "Materialistic.theme.css",
    "midnight": "midnight.theme.css",
    "minimal-cord": "MinimalCord.theme.css",
    "minimal-improvement": "MinimalImprovement.theme.css",
    "minimal-improvement-borderless": "MinimalImprovementBorderless.theme.css",
    "mixpack": "MixPack.theme.css",
    "moon-rabbits": "Moon-Rabbits-Dream-About-Virtual.theme.css",
    "neobrutal": "Neobrutal.theme.css",
    "neptune": "Neptune.theme.css",
    "neutron": "neutron.theme.css",
    "new-akame": "NewAkameGaKill.theme.css",
    "new-bnha": "NewBNHA.theme.css",
    "new-kemono": "NewKemonoFriends.theme.css",
    "new-rem": "NewRemTheme.theme.css",
    "nier-light": "NieR-Light-Source.theme.css",
    "ninex": "NineX.theme.css",
    "noctis-viola": "noctis-viola.theme.css",
    "nocturnal": "nocturnal.theme.css",
    "nord": "Nord.theme.css",
    "nordic": "nordic.theme.css",
    "not-another-anime": "NotAnotherAnimeTheme.theme.css",
    "novum": "Novum.theme.css",
    "nox": "Nox.theme.css",
    "ocean": "Ocean.theme.css",
    "old-akame": "Old-AkameGaKill-Theme.theme.css",
    "old-bnha": "Old-BNHA-Theme.theme.css",
    "oldcord": "OldCord.theme.css",
    "opera-gx": "OperaGX.theme.css",
    "osx": "OSX.theme.css",
    "pesterchum": "Pesterchum.theme.css",
    "pios": "piOS.theme.css",
    "purple-onyx": "PurpleOnyx.theme.css",
    "pyrite": "pyrite.theme.css",
    "quiet": "Quiet.theme.css",
    "radial-status": "RadialStatus.theme.css",
    "rosy-night": "RosyNight.theme.css",
    "rounded-discord": "RoundedDiscord.theme.css",
    "roundmoled": "roundmoled.theme.css",
    "roundmoled-v2": "roundmoledV2.theme.css",
    "settings-modal": "SettingsModal.theme.css",
    "shine": "shine.theme.css",
    "simplify": "simplify.theme.css",
    "skeuocord": "SkeuoCord.theme.css",
    "sleek-cord": "SleekCord.theme.css",
    "softx": "SoftX.theme.css",
    "spectra": "spectra.theme.css",
    "spoticord": "SpotiCord.theme.css",
    "spotify-discord": "Spotify-Discord.theme.css",
    "surcord": "surCord.theme.css",
    "synthesis": "Synthesis.theme.css",
    "system24": "system24.theme.css",
    "t1": "T1.theme.css",
    "theholyonez": "TheHolyOneZ-Dream.theme.css",
    "tokyo-night": "tokyo-night.theme.css",
    "tokyo-midnight": "tokyo_midnight.theme.css",
    "translucence": "Translucence.theme.css",
    "tritone": "Tritone.theme.css",
    "ui-refresh": "UIRefreshRefresh.theme.css",
    "ultra": "Ultra.theme.css",
    "unity": "Unity.theme.css",
    "virtual-boy": "virtual-boy.theme.css",
    "wildberry": "Wildberry.theme.css",
    "wizard-ui": "WizardUI.theme.css",
    "youtube-nation": "Youtube_Nation.theme.css"
};

export const THEME_NAMES = [
    { label: "None (Default DDT)", value: "none" },
    { label: "Aider", value: "aider" },
    { label: "Alan Walker", value: "alan-walker" },
    { label: "Alternative Vista", value: "alternative-vista" },
    { label: "Amethyst", value: "amethyst" },
    { label: "Amoled Cord", value: "amoled-cord" },
    { label: "Azurite", value: "azurite" },
    { label: "Basic Background", value: "basic-background" },
    { label: "Blurple Recolor", value: "blurple-recolor" },
    { label: "Bubble Theme", value: "bubble-theme" },
    { label: "Chillax", value: "chillax" },
    { label: "ClearVision v7", value: "clearvision" },
    { label: "Cursed Cord", value: "cursed-cord" },
    { label: "Cyan", value: "cyan" },
    { label: "Cyberpunk 2077", value: "cyberpunk2077" },
    { label: "Dark+", value: "dark-plus" },
    { label: "Dark Matter", value: "dark-matter" },
    { label: "Dark Neon", value: "dark-neon" },
    { label: "Ddex4", value: "ddex4" },
    { label: "Discord Reborn", value: "discord-reborn" },
    { label: "Discord Mica", value: "discord-mica" },
    { label: "Discord11", value: "discord11" },
    { label: "Discord16", value: "discord16" },
    { label: "Discord Dark", value: "discord-dark" },
    { label: "Discordia", value: "discordia" },
    { label: "Discord Night", value: "discord-night" },
    { label: "Discord Plus", value: "discord-plus" },
    { label: "Discord Recolor", value: "discord-recolor" },
    { label: "DTM-08", value: "dtm-08" },
    { label: "DTM-16", value: "dtm-16" },
    { label: "DTM-18", value: "dtm-18" },
    { label: "Dyslexia", value: "dyslexia" },
    { label: "Emoji Replace", value: "emoji-replace" },
    { label: "Eris", value: "eris" },
    { label: "Exponent", value: "exponent" },
    { label: "Ez Light", value: "ez-light" },
    { label: "Fallout 4 Terminal", value: "fallout4" },
    { label: "Fluent", value: "fluent" },
    { label: "Frosted Glass", value: "frosted-glass" },
    { label: "FVUI", value: "fvui" },
    { label: "GGO Kirito", value: "ggo-kirito" },
    { label: "Glass Wave", value: "glass-wave" },
    { label: "Glass Local", value: "glass-local" },
    { label: "Gruvbox Sharp", value: "gruvbox-sharp" },
    { label: "GX Cord", value: "gxcord" },
    { label: "Horizontal Server List", value: "horizontal-server" },
    { label: "Kaleidoscope", value: "kaleidoscope" },
    { label: "Material Discord", value: "material-discord" },
    { label: "Material Design", value: "material-design" },
    { label: "Materialistic", value: "materialistic" },
    { label: "Midnight", value: "midnight" },
    { label: "Minimal Cord", value: "minimal-cord" },
    { label: "Minimal Improvement", value: "minimal-improvement" },
    { label: "Minimal Improvement Borderless", value: "minimal-improvement-borderless" },
    { label: "Mix Pack", value: "mixpack" },
    { label: "Moon Rabbits Dream", value: "moon-rabbits" },
    { label: "Neobrutal", value: "neobrutal" },
    { label: "Neptune", value: "neptune" },
    { label: "Neutron", value: "neutron" },
    { label: "New Akame Ga Kill", value: "new-akame" },
    { label: "New BNHA", value: "new-bnha" },
    { label: "New Kemono Friends", value: "new-kemono" },
    { label: "New Rem Theme", value: "new-rem" },
    { label: "NieR Light Source", value: "nier-light" },
    { label: "NineX", value: "ninex" },
    { label: "Noctis Viola", value: "noctis-viola" },
    { label: "Nocturnal", value: "nocturnal" },
    { label: "Nord", value: "nord" },
    { label: "Nordic", value: "nordic" },
    { label: "Not Another Anime Theme", value: "not-another-anime" },
    { label: "Novum", value: "novum" },
    { label: "Nox", value: "nox" },
    { label: "Ocean", value: "ocean" },
    { label: "Old Akame Ga Kill", value: "old-akame" },
    { label: "Old BNHA", value: "old-bnha" },
    { label: "OldCord", value: "oldcord" },
    { label: "Opera GX", value: "opera-gx" },
    { label: "OSX", value: "osx" },
    { label: "Pesterchum", value: "pesterchum" },
    { label: "piOS", value: "pios" },
    { label: "Purple Onyx", value: "purple-onyx" },
    { label: "Pyrite", value: "pyrite" },
    { label: "Quiet", value: "quiet" },
    { label: "Radial Status", value: "radial-status" },
    { label: "Rosy Night", value: "rosy-night" },
    { label: "Rounded Discord", value: "rounded-discord" },
    { label: "Roundmoled", value: "roundmoled" },
    { label: "Roundmoled V2", value: "roundmoled-v2" },
    { label: "Settings Modal", value: "settings-modal" },
    { label: "Shine", value: "shine" },
    { label: "Simplify", value: "simplify" },
    { label: "SkeuoCord", value: "skeuocord" },
    { label: "Sleek Cord", value: "sleek-cord" },
    { label: "SoftX", value: "softx" },
    { label: "Spectra", value: "spectra" },
    { label: "SpotiCord", value: "spoticord" },
    { label: "Spotify Discord", value: "spotify-discord" },
    { label: "SurCord", value: "surcord" },
    { label: "Synthesis", value: "synthesis" },
    { label: "System24", value: "system24" },
    { label: "T1", value: "t1" },
    { label: "The Holy OneZ Dream", value: "theholyonez" },
    { label: "Tokyo Night", value: "tokyo-night" },
    { label: "Tokyo Midnight", value: "tokyo-midnight" },
    { label: "Translucence", value: "translucence" },
    { label: "Tritone", value: "tritone" },
    { label: "UI Refresh Refresh", value: "ui-refresh" },
    { label: "Ultra", value: "ultra" },
    { label: "Unity", value: "unity" },
    { label: "Virtual Boy", value: "virtual-boy" },
    { label: "Wildberry", value: "wildberry" },
    { label: "Wizard UI", value: "wizard-ui" },
    { label: "Youtube Nation", value: "youtube-nation" }
];
